version: '2'
services:
    libreria-app:
        image: libreria
        external_links:
            - libreria-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/libreria?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    libreria-mysql:
        extends:
            file: mysql.yml
            service: libreria-mysql
